# Generated by Django 2.1.2 on 2018-10-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='NO IMAGE', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
